arrowParens: 'avoid'
singleQuote: true
bracketSpacing: true
endOfLine: 'lf'
semi: false
tabWidth: 2
trailingComma: 'all'
printWidth: 100
overrides:
  - files: '*.mjs'
    options:
      printWidth: 80
